In [1]:
##installing and importing libraries

In [2]:

!pip install nltk
!pip install spacy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2022.10.31)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.65.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: spacy in /usr/local/lib/python3.10/dist-packages (3.5.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.0.9)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.0.7)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.0.8)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /usr/local/lib/python3.10/dist-packages (from spacy) (8.1.9)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.1.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.4.6)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.0.8)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (0.7.0)
Requirement already satisfied: pathy>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (0.10.1)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy) (6.3.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (4.65.0)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.22.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.27.1)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.10.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (23.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy) (4.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy) (0.7.9)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy) (0.0.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.8.0,>=0.3.0->spacy) (8.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy) (2.1.2)

In [3]:
import numpy as np
import pandas as pd
import re
import nltk
import spacy
import string

In [4]:
##Loading the test data
full_data = pd.read_csv('/content/1429_1.csv', nrows=5000)
full_data.head()

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,This product so far has not disappointed. My c...,Kindle,NaN,NaN,Adapter
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,great for beginner or experienced person. Boug...,very fast,NaN,NaN,truman
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,NaN,NaN,DaveZ
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,I've had my Fire HD 8 two weeks now and I love...,Good!!!,NaN,NaN,Shacks
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,NaN,NaN,explore42

In [5]:
dt = full_data[["reviews.text"]]
dt["reviews.text"] = dt["reviews.text"].astype(str)
from nltk.tokenize import word_tokenize

### Tokenization

nltk.download('punkt')
tokens = dt['reviews.text'].apply(nltk.word_tokenize)
# Print the tokens
print(tokens)

<ipython-input-5-97f82a842d2a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt["reviews.text"] = dt["reviews.text"].astype(str)
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

0       [This, product, so, far, has, not, disappointe...
1       [great, for, beginner, or, experienced, person...
2       [Inexpensive, tablet, for, him, to, use, and, ...
3       [I, 've, had, my, Fire, HD, 8, two, weeks, now...
4       [I, bought, this, for, my, grand, daughter, wh...
                              ...
4995    [Amazing, tablet, for, the, price, i, love, it...
4996    [I, love, my, fire, ..., The, games, and, the,...
4997    [Great, tablet, for, kids, but, the, screen, i...
4998    [Great, product, easy, to, use, ., Having, dif...
4999    [Love, this, tablet, ,, great, price, and, is,...
Name: reviews.text, Length: 5000, dtype: object

In [6]:
full_data.head()

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,This product so far has not disappointed. My c...,Kindle,NaN,NaN,Adapter
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,great for beginner or experienced person. Boug...,very fast,NaN,NaN,truman
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,NaN,NaN,DaveZ
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,I've had my Fire HD 8 two weeks now and I love...,Good!!!,NaN,NaN,Shacks
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,NaN,NaN,explore42

In [7]:
##Lower casing
dt["text_lower"] = dt["reviews.text"].str.lower()
dt.head()

<ipython-input-7-3d6ac7c61541>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt["text_lower"] = dt["reviews.text"].str.lower()

,reviews.text,text_lower
0,This product so far has not disappointed. My c...,this product so far has not disappointed. my c...
1,great for beginner or experienced person. Boug...,great for beginner or experienced person. boug...
2,Inexpensive tablet for him to use and learn on...,inexpensive tablet for him to use and learn on...
3,I've had my Fire HD 8 two weeks now and I love...,i've had my fire hd 8 two weeks now and i love...
4,I bought this for my grand daughter when she c...,i bought this for my grand daughter when she c...

In [8]:
##Removal of punctuation
# drop the new column created in last cell
dt.drop(["text_lower"], axis=1, inplace=True)

PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(reviews_text):
    """custom function to remove the punctuation"""
    return reviews_text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

dt["text_wo_punct"] = dt["reviews.text"].apply(lambda reviews_text: remove_punctuation(reviews_text))
dt.head()

<ipython-input-8-adea8b5fe909>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt.drop(["text_lower"], axis=1, inplace=True)
<ipython-input-8-adea8b5fe909>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt["text_wo_punct"] = dt["reviews.text"].apply(lambda reviews_text: remove_punctuation(reviews_text))

,reviews.text,text_wo_punct
0,This product so far has not disappointed. My c...,This product so far has not disappointed My ch...
1,great for beginner or experienced person. Boug...,great for beginner or experienced person Bough...
2,Inexpensive tablet for him to use and learn on...,Inexpensive tablet for him to use and learn on...
3,I've had my Fire HD 8 two weeks now and I love...,Ive had my Fire HD 8 two weeks now and I love ...
4,I bought this for my grand daughter when she c...,I bought this for my grand daughter when she c...

In [9]:
##Removal of stopwords

In [10]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [11]:
from nltk.corpus import stopwords
", ".join(stopwords.words('english'))

"i, me, my, myself, we, our, ours, ourselves, you, you're, you've, you'll, you'd, your, yours, yourself, yourselves, he, him, his, himself, she, she's, her, hers, herself, it, it's, its, itself, they, them, their, theirs, themselves, what, which, who, whom, this, that, that'll, these, those, am, is, are, was, were, be, been, being, have, has, had, having, do, does, did, doing, a, an, the, and, but, if, or, because, as, until, while, of, at, by, for, with, about, against, between, into, through, during, before, after, above, below, to, from, up, down, in, out, on, off, over, under, again, further, then, once, here, there, when, where, why, how, all, any, both, each, few, more, most, other, some, such, no, nor, not, only, own, same, so, than, too, very, s, t, can, will, just, don, don't, should, should've, now, d, ll, m, o, re, ve, y, ain, aren, aren't, couldn, couldn't, didn, didn't, doesn, doesn't, hadn, hadn't, hasn, hasn't, haven, haven't, isn, isn't, ma, mightn, mightn't, mustn, mustn't, needn, needn't, shan, shan't, shouldn, shouldn't, wasn, wasn't, weren, weren't, won, won't, wouldn, wouldn't"

In [12]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(reviews_text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(reviews_text).split() if word not in STOPWORDS])

dt["text_wo_stop"] = dt["text_wo_punct"].apply(lambda reviews_text: remove_stopwords(reviews_text))
dt.head()

<ipython-input-12-4ac466d30b8d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt["text_wo_stop"] = dt["text_wo_punct"].apply(lambda reviews_text: remove_stopwords(reviews_text))

,reviews.text,text_wo_punct,text_wo_stop
0,This product so far has not disappointed. My c...,This product so far has not disappointed My ch...,This product far disappointed My children love...
1,great for beginner or experienced person. Boug...,great for beginner or experienced person Bough...,great beginner experienced person Bought gift ...
2,Inexpensive tablet for him to use and learn on...,Inexpensive tablet for him to use and learn on...,Inexpensive tablet use learn step NABI He thri...
3,I've had my Fire HD 8 two weeks now and I love...,Ive had my Fire HD 8 two weeks now and I love ...,Ive Fire HD 8 two weeks I love This tablet gre...
4,I bought this for my grand daughter when she c...,I bought this for my grand daughter when she c...,I bought grand daughter comes visit I set user...

In [13]:
## Removal of frequent word

In [14]:
from collections import Counter
cnt = Counter()
for text in dt["text_wo_stop"].values:
    for word in text.split():
        cnt[word] += 1

cnt.most_common(10)

[('I', 4381),
 ('tablet', 2015),
 ('great', 1248),
 ('use', 1113),
 ('price', 926),
 ('The', 887),
 ('good', 743),
 ('This', 741),
 ('Kindle', 708),
 ('one', 686)]

In [15]:
FREQWORDS = set([w for (w, wc) in cnt.most_common(10)])
def remove_freqwords(text):
    """custom function to remove the frequent words"""
    return " ".join([word for word in str(text).split() if word not in FREQWORDS])

dt["text_wo_stopfreq"] = dt["text_wo_stop"].apply(lambda text: remove_freqwords(text))
dt.head()

<ipython-input-15-c981024f35eb>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt["text_wo_stopfreq"] = dt["text_wo_stop"].apply(lambda text: remove_freqwords(text))

,reviews.text,text_wo_punct,text_wo_stop,text_wo_stopfreq
0,This product so far has not disappointed. My c...,This product so far has not disappointed My ch...,This product far disappointed My children love...,product far disappointed My children love like...
1,great for beginner or experienced person. Boug...,great for beginner or experienced person Bough...,great beginner experienced person Bought gift ...,beginner experienced person Bought gift loves
2,Inexpensive tablet for him to use and learn on...,Inexpensive tablet for him to use and learn on...,Inexpensive tablet use learn step NABI He thri...,Inexpensive learn step NABI He thrilled learn ...
3,I've had my Fire HD 8 two weeks now and I love...,Ive had my Fire HD 8 two weeks now and I love ...,Ive Fire HD 8 two weeks I love This tablet gre...,Ive Fire HD 8 two weeks love valueWe Prime Mem...
4,I bought this for my grand daughter when she c...,I bought this for my grand daughter when she c...,I bought grand daughter comes visit I set user...,bought grand daughter comes visit set user ent...

In [16]:
## Removal of rare words

In [17]:
# Drop the two columns which are no more needed
dt.drop(["text_wo_punct", "text_wo_stop"], axis=1, inplace=True)

n_rare_words = 10
RAREWORDS = set([w for (w, wc) in cnt.most_common()[:-n_rare_words-1:-1]])
def remove_rarewords(text):
    """custom function to remove the rare words"""
    return " ".join([word for word in str(text).split() if word not in RAREWORDS])

dt["text_wo_stopfreqrare"] = dt["text_wo_stopfreq"].apply(lambda text: remove_rarewords(text))
dt.head()

<ipython-input-17-a2cca37ebf83>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt.drop(["text_wo_punct", "text_wo_stop"], axis=1, inplace=True)
<ipython-input-17-a2cca37ebf83>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt["text_wo_stopfreqrare"] = dt["text_wo_stopfreq"].apply(lambda text: remove_rarewords(text))

,reviews.text,text_wo_stopfreq,text_wo_stopfreqrare
0,This product so far has not disappointed. My c...,product far disappointed My children love like...,product far disappointed My children love like...
1,great for beginner or experienced person. Boug...,beginner experienced person Bought gift loves,beginner experienced person Bought gift loves
2,Inexpensive tablet for him to use and learn on...,Inexpensive learn step NABI He thrilled learn ...,Inexpensive learn step NABI He thrilled learn ...
3,I've had my Fire HD 8 two weeks now and I love...,Ive Fire HD 8 two weeks love valueWe Prime Mem...,Ive Fire HD 8 two weeks love valueWe Prime Mem...
4,I bought this for my grand daughter when she c...,bought grand daughter comes visit set user ent...,bought grand daughter comes visit set user ent...

In [19]:
##Lemmatization

In [20]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [22]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

dt["text_lemmatized"] = dt["reviews.text"].apply(lambda text: lemmatize_words(text))
dt.head()

<ipython-input-22-6c59e294ac6f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt["text_lemmatized"] = dt["reviews.text"].apply(lambda text: lemmatize_words(text))

,reviews.text,text_wo_stopfreq,text_wo_stopfreqrare,text_lemmatized
0,This product so far has not disappointed. My c...,product far disappointed My children love like...,product far disappointed My children love like...,This product so far ha not disappointed. My ch...
1,great for beginner or experienced person. Boug...,beginner experienced person Bought gift loves,beginner experienced person Bought gift loves,great for beginner or experienced person. Boug...
2,Inexpensive tablet for him to use and learn on...,Inexpensive learn step NABI He thrilled learn ...,Inexpensive learn step NABI He thrilled learn ...,Inexpensive tablet for him to use and learn on...
3,I've had my Fire HD 8 two weeks now and I love...,Ive Fire HD 8 two weeks love valueWe Prime Mem...,Ive Fire HD 8 two weeks love valueWe Prime Mem...,I've had my Fire HD 8 two week now and I love ...
4,I bought this for my grand daughter when she c...,bought grand daughter comes visit set user ent...,bought grand daughter comes visit set user ent...,I bought this for my grand daughter when she c...

In [23]:
## Stemming

In [24]:
from nltk.stem.porter import PorterStemmer

# Drop the two columns
dt.drop(["text_wo_stopfreq", "text_wo_stopfreqrare"], axis=1, inplace=True)

stemmer = PorterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

dt["text_stemmed"] = dt["reviews.text"].apply(lambda text: stem_words(text))
dt.head()

<ipython-input-24-c96158ce09f6>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt.drop(["text_wo_stopfreq", "text_wo_stopfreqrare"], axis=1, inplace=True)
<ipython-input-24-c96158ce09f6>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt["text_stemmed"] = dt["reviews.text"].apply(lambda text: stem_words(text))

,reviews.text,text_lemmatized,text_stemmed
0,This product so far has not disappointed. My c...,This product so far ha not disappointed. My ch...,thi product so far ha not disappointed. my chi...
1,great for beginner or experienced person. Boug...,great for beginner or experienced person. Boug...,great for beginn or experienc person. bought a...
2,Inexpensive tablet for him to use and learn on...,Inexpensive tablet for him to use and learn on...,"inexpens tablet for him to use and learn on, s..."
3,I've had my Fire HD 8 two weeks now and I love...,I've had my Fire HD 8 two week now and I love ...,i'v had my fire hd 8 two week now and i love i...
4,I bought this for my grand daughter when she c...,I bought this for my grand daughter when she c...,i bought thi for my grand daughter when she co...